
DROP TABLE IF EXISTS kantopokedex;

CREATE TABLE kantopokedex(
    pokedex_num SERIAL PRIMARY KEY NOT NULL,
    Name VARCHAR(50) NOT NULL,
    Category VARCHAR(50) NOT NULL,
    Type_1 VARCHAR(50) NOT NULL,
    Type_2 VARCHAR(50),
    Description VARCHAR(1000) NOT NULL
);


INSERT INTO kantopokedex(pokedex_num, name, Category, type_1, type_2, description) VALUES
(001, 'Bulbasaur', 'Seed Pokemon', 'Grass', 'Poison', 'There is a plant seed on its back right from the day this Pokémon is born. The seed slowly grows larger.'),
(002, 'Ivysaur', 'Seed Pokemon', 'Grass', 'Poison', 'When the bulb on its back grows large, it appears to lose the ability to stand on its hind legs.'),
(003, 'Venusaur', 'Seed Pokemon', 'Grass', 'Poison', 'The plant blooms when it is absorbing solar energy. It stays on the move to seek sunlight.'),
(004, 'Charmander', 'Lizard Pokemon', 'Fire', null, 'Obviously prefers hot places. When it rains, steam is said to spout from the tip of its tail.'),
(005, 'Charmeleon', 'Flame Pokemon', 'Fire', null, 'When it swings its burning tail, it elevates the temperature to unbearably high levels.'),
(006, 'Charizard', 'Flame Pokemon', 'Fire', 'Flying', 'Spits fire that is hot enough to melt boulders. Known to cause forest fires unintentionally.'),
(007, 'Squirtle', 'Tiny Turtle Pokemon', 'Water', null, 'After birth, its back swells and hardens into a shell. Powerfully sprays foam from its mouth.'),
(008, 'Wartortle', 'Turtle Pokemon', 'Water', null, 'Often hides in water to stalk unwary prey. For swimming fast, it moves its ears to maintain balance.'),
(009, 'Blastoise', 'Shellfish Pokemon', 'Water', null, 'A brutal Pokémon with pressurized water jets on its shell. They are used for high speed tackles.'),
(010, 'Caterpie', 'Worm Pokemon', 'Bug', null, 'Its short feet are tipped with suction pads that enable it to tirelessly climb slopes and walls.'),
(011, 'Metapod', 'Cocoon Pokemon', 'Bug', null, 'This Pokémon is vulnerable to attack while its shell is soft, exposing its weak and tender body.'),
(012, 'Butterfree', 'Butterfly Pokemon', 'Bug', 'Flying', 'In battle, it flaps its wings at high speed to release highly toxic dust into the air.'),
(013, 'Weedle', 'Hairy Bug Pokemon', 'Bug', 'Poison', 'Often found in forests, eating leaves. It has a sharp venomous stinger on its head.'),
(014, 'Kakuna', 'Cocoon Pokemon', 'Bug', 'Poison', 'Almost incapable of moving, this Pokémon can only harden its shell to protect itself from predators.'),
(015, 'Beedrill', 'Poison Bee Pokemon', 'Bug', 'Poison', 'Flies at high speed and attacks using its large venomous stingers on its forelegs and tail.'),
(016, 'Pidgey', 'Tiny Bird Pokeomn', 'Normal', 'Flying', 'A common sight in forests and woods. It flaps its wings at ground level to kick up blinding sand.'),
(017, 'Pidgeotto', 'Bird Pokemon', 'Normal', 'Flying', 'Very protective of its sprawling territorial area, this Pokémon will fiercely peck at any intruder.'),
(018, 'Pidgeot', 'Bird Pokemon', 'Normal', 'Flying', 'When hunting, it skims the surface of water at high speed to pick off unwary prey such as Magikarp.'),
(019, 'Rattata', 'Mouse Pokeomn', 'Normal', null, 'Bites anything when it attacks. Small and very quick, it is a common sight in many places.'),
(020, 'Raticate', 'Mouse Pokeomn', 'Normal', null, 'It uses its whiskers to maintain its balance. It apparently slows down if they are cut off.'),
(021, 'Spearow', 'Tiny Bird Pokemon', 'Normal', 'Flying', 'Eats bugs in grassy areas. It has to flap its short wings at high speed to stay airborne.'),
(022, 'Fearow', 'Beak Pokemon', 'Normal', 'Flying', 'With its huge and magnificent wings, it can keep aloft without ever having to land for rest.'),
(023, 'Ekans', 'Snake Pokemon', 'Poison', null, 'Moves silently and stealthily. Eats the eggs of birds, such as Pidgey and Spearow, whole.'),
(024, 'Arbok', 'Cobra Pokemon', 'Poison', null, 'It is rumored that the ferocious warning markings on its belly differ from area to area.'),
(025, 'Pikachu', 'Mouse Pokemon', 'Electric', null, 'When several of these Pokémon gather, their electricity could build and cause lightning storms.'),
(026, 'Raichu', 'Mouse Pokemon', 'Electric', null, 'Its long tail serves as a ground to protect itself from its own high voltage power.'),
(027, 'Sandshrew', 'Mouse Pokemon', 'Ground', null, 'Burrows deep underground in arid locations far from water. It only emerges to hunt for food.'),
(028, 'Sandslash', 'Mouse Pokemon', 'Ground', null, 'Curls up into a spiny ball when threatened. It can roll while curled up to attack or escape.'),
(029, 'Nidoran(f)', 'Poison Pin Pokemon', 'Poison', null, 'Although small, its venomous barbs render this Pokémon dangerous. The female has smaller horns.'),
(030, 'Nidorina', 'Poison Pin Pokemon', 'Poison', null, 'The females horn develops slowly. Prefers physical attacks such as clawing and biting.'),
(031, 'Nidoqueen', 'Drill Pokemon', 'Poison', 'Ground', 'Its hard scales provide strong protection. It uses its hefty bulk to execute powerful moves.'),
(032, 'Nidoran(m)', 'Poison Pin Pokemon', 'Poison', null, 'Stiffens its ears to sense danger. The larger its horns, the more powerful its secreted venom.'),
(033, 'Nidorino', 'Poison Pin Pokemon', 'Poison', null, 'An aggressive Pokémon that is quick to attack. The horn on its head secretes a powerful venom.'),
(034, 'Nidoking', 'Drill Pokemon', 'Poison', 'Ground', 'It uses its powerful tail in battle to smash, constrict, then break the preys bones.'),
(035, 'Clefairy', 'Fairy Pokemon', 'Fairy', null, 'Its magical and cute appeal has many admirers. It is rare and found only in certain areas.'),
(036, 'Clefable', 'Fairy Pokemon', 'Fairy', null, 'A timid fairy Pokémon that is rarely seen. It will run and hide the moment it senses people.'),
(037, 'Vulpix', 'Fox Pokemon', 'Fire', null, 'At the time of birth, it has just one tail. The tail splits from its tip as it grows older.'),
(038, 'Ninetales', 'Fox Pokemon', 'Fire', null, 'Very smart and very vengeful. Grabbing one of its many tails could result in a 1000-year curse.'),
(039, 'Jigglypuff', 'Balloon Pokemon', 'Normal', 'Fairy', 'When its huge eyes light up, it sings a mysteriously soothing melody that lulls its enemies to sleep.'),
(040, 'Wigglytuff', 'Balloon Pokemon', 'Normal', 'Fairy', 'The body is soft and rubbery. When angered, it will suck in air and inflate itself to an enormous size.'),
(041, 'Zubat', 'Bat Pokemon', 'Poison', 'Flying', 'Forms colonies in perpetually dark places. Uses ultrasonic waves to identify and approach targets.'),
(042, 'Golbat', 'Bat Pokemon', 'Poison', 'Flying', 'Once it strikes, it will not stop draining energy from the victim even if it gets too heavy to fly.'),
(043, 'Oddish', 'Weed Pokemon', 'Grass', 'Poison', 'During the day, it keeps its face buried in the ground. At night, it wanders around sowing its seeds.'),
(044, 'Gloom', 'Weed Pokemon', 'Grass', 'Poison', 'The fluid that oozes from its mouth isnt drool. It is a nectar that is used to attract prey.'),
(045, 'Vileplume', 'Flower Pokemon', 'Grass', 'Poison', 'The larger its petals, the more toxic pollen it contains. Its big head is heavy and hard to hold up.'),
(046, 'Paras', 'Mushroom Pokemon', 'Bug', 'Grass', 'Burrows to suck tree roots. The mushrooms on its back grow by drawing nutrients from the bug host.'),
(047, 'Parasect', 'Mushroom Pokemon', 'Bug', 'Grass', 'A host-parasite pair in which the parasite mushroom has taken over the host bug. Prefers damp places.'),
(048, 'Venonat', 'Insect Pokemon', 'Bug', 'Poison', 'Lives in the shadows of tall trees where it eats insects. It is attracted by light at night.'),
(049, 'Venomoth', 'Poison Moth Pokemon', 'Bug', 'Poison', 'The dust-like scales covering its wings are color coded to indicate the kinds of poison it has.'),
(050, 'Diglett', 'Mole Pokemon', 'Ground', null, 'Lives about one yard underground where it feeds on plant roots. It sometimes appears above ground.'),
(051, 'Dugtrio', 'Mole Pokemon', 'Ground', null, 'A team of Diglett triplets. It triggers huge earthquakes by burrowing 60 miles underground.'),
(052, 'Meowth', 'Cat Scratch Pokemon', 'Normal', null, 'Adores circular objects. Wanders the streets on a nightly basis to look for dropped loose change.'),
(053, 'Persian', 'Classy Cat Pokemon', 'Normal', null, 'Although its fur has many admirers, it is tough to raise as a pet because of its fickle meanness.'),
(054, 'Psyduck', 'Duck Pokemon', 'Water', null, 'While lulling its enemies with its vacant look, this wily Pokémon will use psychokinetic powers.'),
(055, 'Golduck', 'Duck Pokemon', 'Water', null, 'Often seen swimming elegantly by lake shores. It is often mistaken for the Japanese monster, Kappa.'),
(056, 'Mankey', 'Pig Monkey Pokemon', 'Fighting', null, 'Extremely quick to anger. It could be docile one moment then thrashing away the next instant.'),
(057, 'Primeape', 'Pig Monkey Pokemon', 'Fighting', null, 'Always furious and tenacious to boot. It will not abandon chasing its quarry until it is caught.'),
(058, 'Growlithe', 'Puppy Pokemon', 'Fire', null, 'Very protective of its territory. It will bark and bite to repel intruders from its space.'),
(059, 'Arcanine', 'Legendary Pokemon', 'Fire', null, 'A Pokémon that has been admired since the past for its beauty. It runs agilely as if on wings.'),
(060, 'Polywag', 'Tadpole Pokemon', 'Water', null, 'Its newly grown legs prevent it from running. It appears to prefer swimming than trying to stand.'),
(061, 'Polywhirl', 'Tadpole Pokemon', 'Water', null, 'Capable of living in or out of water. When out of water, it sweats to keep its body slimy.'),
(062, 'Polywrath', 'Tadpole Pokemon', 'Water', 'Fighting', 'An adept swimmer at both the front crawl and breast stroke. Easily overtakes the best human swimmers.'),
(063, 'Abra', 'Psi Pokemon', 'Psychic', null, 'Using its ability to read minds, it will identify impending danger and teleport to safety.'),
(064, 'Kadabra', 'Psi Pokemon', 'Psychic', null, 'It emits special alpha waves from its body that induce headaches just by being close by.'),
(065, 'Alakazam', 'Psi Pokemon', 'Psychic', null, 'Its brain can outperform a super-computer. Its intelligence quotient is said to be 5,000.'),
(066, 'Machop', 'Superpower Pokemon', 'Fighting', null, 'Loves to build its muscles. It trains in all styles of martial arts to become even stronger.'),
(067, 'Machoke', 'Superpower Pokemon', 'Fighting', null, 'Its muscular body is so powerful, it must wear a power save belt to be able to regulate its motions.'),
(068, 'Machamp', 'Superpower Pokemon', 'Fighting', null, 'Using its heavy muscles, it throws powerful punches that can send the victim clear over the horizon.'),
(069, 'Bellsprout', 'Flower Pokemon', 'Grass', 'Poison', 'A carnivorous Pokémon that traps and eats bugs. It uses its root feet to soak up needed moisture.'),
(070, 'Weepinbell', 'Flycatcher Pokemon', 'Grass', 'Poison', 'It spits out PoisonPowder to immobilize the enemy and then finishes it with a spray of Acid.'),
(071, 'Victreebel', 'Flycatcher Pokemon', 'Grass', 'Poison', 'Said to live in huge colonies deep in jungles, although no one has ever returned from there.'),
(072, 'Tentacool', 'Jellyfish Pokemon', 'Water', 'Poison', 'Drifts in shallow seas. Anglers who hook them by accident are often punished by its stinging acid.'),
(073, 'Tentacruel', 'Jellyfish Pokemon', 'Water', 'Poison', 'The tentacles are normally kept short. On hunts, they are extended to ensnare and immobilize prey.'),
(074, 'Geodude', 'Rock Pokemon', 'Rock', 'Ground', 'Found in fields and mountains. Mistaking them for boulders, people often step or trip on them.'),
(075, 'Graveler', 'Rock Pokemon', 'Rock', 'Ground', 'Rolls down slopes to move. It rolls over any obstacle without slowing or changing its direction.'),
(076, 'Golem', 'Megaton Pokemon', 'Rock', 'Ground', 'Its boulder-like body is extremely hard. It can easily withstand dynamite blasts without damage.'),
(077, 'Ponyta', 'Fire Horse Pokemon', 'Fire', null, 'Its hooves are 10 times harder than diamonds. It can trample anything completely flat in little time.'),
(078, 'Rapidash', 'Fire Horse Pokemon', 'Fire', null, 'Very competitive, this Pokémon will chase anything that moves fast in the hopes of racing it.'),
(079, 'Slowpoke', 'Dopey Pokemon', 'Water', 'Psychic', 'Incredibly slow and dopey. It takes 5 seconds for it to feel pain when under attack.'),
(080, 'Slowbro', 'Hermit Crab Pokemon', 'Water', 'Psychic', 'The Shellder that is latched onto Slowpokes tail is said to feed on the hosts left over scraps.'),
(081, 'Magnemite', 'Magnet Pokemon', 'Electric', 'Steel', 'Uses anti-gravity to stay suspended. Appears without warning and uses Thunder Wave and similar moves.'),
(082, 'Magneton', 'Magnet Pokemon', 'Electric', 'Steel', 'Formed by several Magnemites linked together. They frequently appear when sunspots flare up.'),
(083, 'Farfetchd', 'Wild Duck Pokemon', 'Normal', 'Flying', 'The sprig of green onions it holds is its weapon. It is used much like a metal sword.'),
(084, 'Doduo', 'Twin Bird Pokemon', 'Normal', 'Flying','A bird that makes up for its poor flying with its fast foot speed. Leaves giant footprints.'),
(085, 'Dodrio', 'Triple Bird Pokemon', 'Normal', 'Flying', 'Uses its three brains to execute complex plans. While two heads sleep, one head stays awake.'),
(086, 'Seel', 'Sea Lion Pokemon', 'Water', null, 'The protruding horn on its head is very hard. It is used for bashing through thick ice.'),
(087, 'Dewgong', 'Sea Lion Pokemon', 'Water', 'Ice', 'Stores thermal energy in its body. Swims at a steady 8 knots even in intensely cold waters.'),
(088, 'Grimer', 'Sludge Pokemon', 'Poison', null, 'Appears in filthy areas. Thrives by sucking up polluted sludge that is pumped out of factories.'),
(089, 'Muk', 'Sludge Pokemon', 'Poison', null, 'Thickly covered with a filthy, vile sludge. It is so toxic, even its footprints contain poison.'),
(090, 'Shellder', 'Bivalve Pokemon', 'Water', null, 'Its hard shell repels any kind of attack. It is vulnerable only when its shell is open.'),
(091, 'Cloyster', 'Bivalve Pokemon', 'Water', 'Ice', 'When attacked, it launches its horns in quick volleys. Its innards have never been seen.'),
(092, 'Gastly', 'Gas Pokemon', 'Ghost', 'Poison', 'Almost invisible, this gaseous Pokémon cloaks the target and puts it to sleep without notice.'),
(093, 'Haunter', 'Gas Pokemon', 'Ghost', 'Poison', 'Because of its ability to slip through block walls, it is said to be from another dimension.'),
(094, 'Gengar', 'Shadow Pokemon', 'Ghost', 'Poison', 'Under a full moon, this Pokémon likes to mimic the shadows of people and laugh at their fright.'),
(095, 'Onix', 'Rock Snake Pokemon', 'Rock', 'Ground', 'As it grows, the stone portions of its body harden to become similar to a diamond, but colored black.'),
(096, 'Drowzee', 'Hypnosis Pokemon', 'Psychic', null, 'Puts enemies to sleep then eats their dreams. Occasionally gets sick from eating bad dreams.'),
(097, 'Hypno', 'Hypnosis Pokemon', 'Psychic', null, 'When it locks eyes with an enemy, it will use a mix of PSI moves such as Hypnosis and Confusion.'),
(098, 'Krabby', 'River Crab Pokemon', 'Water', null, 'Its pincers are not only powerful weapons, they are used for balance when walking sideways.'),
(099, 'Kingler', 'Pincer Pokemon', 'Water', null, 'The large pincer has 10000-HP of crushing power. However, its huge size makes it unwieldy to use.'),
(100, 'Voltorb', 'Ball Pokemon', 'Electric', null, 'Usually found in power plants. Easily mistaken for a Poké Ball, they have zapped many people'),
(101, 'Electrode', 'Ball Pokemon', 'Electric', null, 'It stores electric energy under very high pressure. It often explodes with little or no provocation.'),
(102, 'Exeggcute', 'Egg Pokemon', 'Grass', 'Psychic', 'Often mistaken for eggs. When disturbed, they quickly gather and attack in swarms.'),
(103, 'Exeggutor', 'Coconut Pokemon', 'Grass', 'Psychic', 'Legend has it that on rare occasions, one of its heads will drop off and continue on as an Exeggcute.'),
(104, 'Cubone', 'Lonely Pokemon', 'Ground', null, 'Because it never removes its skull helmet, no one has ever seen this Pokémons real face.'),
(105, 'Marowak', 'Bone Keeper Pokemon', 'Ground', null, 'The bone it holds is its key weapon. It throws the bone skillfully like a boomerang to KO targets.'),
(106, 'Hitmonlee', 'Kicking Pokemon', 'Fighting', null, 'When in a hurry, its legs lengthen progressively. It runs smoothly with extra long, loping strides.'),
(107, 'Hitmonchan', 'Punching Pokemon', 'Fighting', null, 'While apparently doing nothing, it fires punches in lightning fast volleys that are impossible to see.'),
(108, 'Lickitung', 'Licking Pokemon', 'Normal', null, 'Its tongue can be extended like a chameleons. It leaves a tingling sensation when it licks enemies.'),
(109, 'Koffing', 'Poison Gas Pokemon', 'Poison', null, 'Because it stores several kinds of toxic gases in its body, it is prone to exploding without warning.'),
(110, 'Weezing', 'Poison Gas Pokemon', 'Poison', null, 'Where two kinds of poison gases meet, 2 Koffings can fuse into a Weezing over many years.'),
(111, 'Rhyhorn', 'Spikes Pokemon', 'Ground', 'Rock', 'Its massive bones are 1000 times harder than human bones. It can easily knock a trailer flying.'),
(112, 'Rhydon', 'Drill Pokemon', 'Ground', 'Rock', 'Protected by an armor-like hide, it is capable of living in molten lava of 3,600 degrees.'),
(113, 'Chansey', 'Egg Pokemon', 'Normal', null, 'A rare and elusive Pokémon that is said to bring happiness to those who manage to get it.'),
(114, 'Tangela', 'Vine Pokemon', 'Grass', null, 'The whole body is swathed with wide vines that are similar to seaweed. Its vines shake as it walks.'),
(115, 'Kengaskhan', 'Parent Pokemon', 'Normal', null, 'The infant rarely ventures out of its mothers protective pouch until it is 3 years old.'),
(116, 'Horsea', 'Dragon Pokemon', 'Water', null, 'Known to shoot down flying bugs with precision blasts of ink from the surface of the water.'),
(117, 'Seadra', 'Dragon Pokemon', 'Water', null, 'Capable of swimming backwards by rapidly flapping its wing-like pectoral fins and stout tail.'),
(118, 'Goldeen', 'Goldfish Pokemon', 'Water', null, 'ts tail fin billows like an elegant ballroom dress, giving it the nickname of the Water Queen.'),
(119, 'Seaking', 'Goldfish Pokemon', 'Water', null, 'In the autumn spawning season, they can be seen swimming powerfully up rivers and creeks.'),
(120, 'Staryu', 'Star Shape Pokemon', 'Water', null, 'An enigmatic Pokémon that can effortlessly regenerate any appendage it loses in battle.'),
(121, 'Starmie', 'Mysterious Pokemon', 'Water', 'Psychic', 'Its central core glows with the seven colors of the rainbow. Some people value the core as a gem.'),
(122, 'Mr. Mime', 'Barrier Pokemon', 'Psychic', 'Fairy', 'If interrupted while it is miming, it will slap around the offender with its broad hands.'),
(123, 'Scyther', 'Mantis Pokemon', 'Bug', 'Flying', 'With ninja-like agility and speed, it can create the illusion that there is more than one.'),
(124, 'Jynx', 'Human Shape Pokemon', 'Ice', 'Psychic', 'It seductively wiggles its hips as it walks. It can cause people to dance in unison with it.'),
(125, 'Electabuzz', 'Electric Pokemon', 'Electric', null, 'Normally found near power plants, they can wander away and cause major blackouts in cities.'),
(126, 'Magmar', 'Spitfire Pokemon', 'Fire', null, 'Its body always burns with an orange glow that enables it to hide perfectly among flames.'),
(127, 'Pinsir', 'Stag Beetle Pokemon', 'Bug', null, 'If it fails to crush the victim in its pincers, it will swing it around and toss it hard.'),
(128, 'Tauros', 'Wild Bull Pokemon', 'Normal', null, 'When it targets an enemy, it charges furiously while whipping its body with its long tails.'),
(129, 'Magikarp', 'Fish Pokemon', 'Water', null, 'In the distant past, it was somewhat stronger than the horribly weak descendants that exist today.'),
(130, 'Gyarados', 'Atrocious Pokemon', 'Water', 'Flying', 'Rarely seen in the wild. Huge and vicious, it is capable of destroying entire cities in a rage.'),
(131, 'Lapras', 'Transport Pokeomn', 'Water', 'Ice', 'A Pokémon that has been overhunted almost to extinction. It can ferry people across the water.'),
(132, 'Ditto', 'Transform Pokemon', 'Normal', null, 'Capable of copying an enemys genetic code to instantly transform itself into a duplicate of the enemy.'),
(133, 'Eevee', 'Evolution Pokemon', 'Normal', null, 'Its genetic code is irregular. It may mutate if it is exposed to radiation from Evolution stones.'),
(134, 'Vaporeon', 'Bubble Jet Pokemon', 'Water', null, 'Lives close to water. Its long tail is ridged with a fin which is often mistaken for a mermaids.'),
(135, 'Jolteon', 'Lightning Pokemon', 'Electric', null, 'It accumulates negative ions in the atmosphere to blast out 10000-volt lightning bolts.'),
(136, 'Flareon', 'Flame Pokemon', 'Fire', null, 'When storing thermal energy in its body, its temperature could soar to over 1600 degrees.'),
(137, 'Porygon', 'Virtual Pokemon', 'Normal', null, 'A Pokémon that consists entirely of programming code. Capable of moving freely in cyberspace'),
(138, 'Omanyte', 'Spiral Pokeomn', 'Rock', 'Water', 'Although long extinct, in rare cases, it can be genetically resurrected from fossils.'),
(139, 'Omastar', 'Spiral Pokeomn', 'Rock', 'Water', 'A prehistoric Pokémon that died out when its heavy shell made it impossible to catch prey.'),
(140, 'Kabuto', 'Shellfish Pokemon', 'Rock', 'Water', 'A Pokémon that was resurrected from a fossil found in what was once the ocean floor eons ago.'),
(141, 'Kabutops', 'Shellfish Pokemon', 'Rock', 'Water', 'Its sleek shape is perfect for swimming. It slashes prey with its claws and drains the body fluids.'),
(142, 'Aerodactyl', 'Fossil Pokemon', 'Rock', 'Flying', 'A ferocious, prehistoric Pokémon that goes for the enemys throat with its serrated saw-like fangs.'),
(143, 'Snorlax', 'Sleeping People', 'Normal', null, 'Very lazy. Just eats and sleeps. As its rotund bulk builds, it becomes steadily more slothful.'),
(144, 'Articuno', 'Freeze Pokemon', 'Ice', 'Flying', 'A legendary bird Pokémon that is said to appear to doomed people who are lost in icy mountains.'),
(145, 'Zapdos', 'Electric Pokemon', 'Electric', 'Flying', 'A legendary bird Pokémon that is said to appear from clouds while dropping enormous lightning bolts.'),
(146, 'Moltres', 'Flame Pokemon', 'Fire', 'Flying', 'Known as the legendary bird of fire. Every flap of its wings creates a dazzling flash of flames.'),
(147, 'Dratini', 'Dragon Pokemon', 'Dragon', null, 'Long considered a mythical Pokémon until recently when a small colony was found living underwater.'),
(148, 'Dragonair', 'Dragon Pokemon', 'Dragon', null, 'A mystical Pokémon that exudes a gentle aura. Has the ability to change climate conditions.'),
(149, 'Dragonite', 'Dragon Pokemon', 'Dragon', 'Flying', 'An extremely rarely seen marine Pokémon. Its intelligence is said to match that of humans.'),
(150, 'Mewtwo', 'Genetic Pokemon', 'Psychic', null, 'It was created by a scientist after years of horrific gene splicing and DNA engineering experiments.'),
(151, 'Mew', 'New Species Pokemon', 'Psychic', null, 'So rare that it is still said to be a mirage by many experts. Only a few people have seen it worldwide.');

SELECT * FROM kantopokedex;
